# Site settings
title: unmonoqueteclea
description: 'A monkey hitting keys at random on a typewriter keyboard
for an infinite amount of time will almost surely type this
blog.'
subdescription: 'Technology | Machine Learning | Music'
subsubdescription: 'From Valencia (Spain)'
url: 'https://unmonoqueteclea.github.io/'
baseurl: ''
google_analytics: 'UA-102906314-1'
disqus_shortname: 'unmonoqueteclea'

author:
  name: 'Pablo González Carrizo'
  email: pgonzalezcarrizo@gmail.com
  twitter_username: unmonoqueteclea
  github_username:  unmonoqueteclea
  linkedin_username: pgonzalezcarrizo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
