#+title: About
#+date: <2024-03-21 19:01>
#+description:
#+filetags: me

* unmonoqueteclea
🐒 =unmonoqueteclea= means *typing monkey* (in Spanish).
And [[https://en.wikipedia.org/wiki/Infinite_monkey_theorem][this Wikipedia entry]] will help you understand it. Although you will find
me everywhere as =unmonoqueteclea=, my name is *Pablo González Carrizo*.

Most of my knowledge comes from other people that made her thoughts or
code public, I am morally obliged to do my bit.


* Work
My CV says I have a =MSc Degree in Telecommunications Engineering=. For
the last few years, I have been working as a =Lead Software Engineer=,
trying to *democratize Machine Learning* 🤖 at [[https://bigml.com][BigML]].

I consider myself an *end-to-end engineer*, the kind of person that can
transform ideas into working prototypes in a few nights fueled with
some cups of tea.

You can also check my [[./static/cv.pdf][CV]] and my [[./awards.html][awards]]  🏆.

* Contact
Feel free to contact me at =unmonoqueteclea@gmail.com= or at any of the
social networks listed in the page footer.
