#+title: towards minimalism
#+date: <2022-12-26 12:00>
#+description: I moved the blog to a simple static blog generator with no dependencies
#+filetags: blogging

*tldr* I moved the blog to an extremely simple static blog generator
with no dependencies, no =Javascript= and no magic tricks. Just plain
=HTML= and =CSS=. You can find the code [[https://github.com/unmonoqueteclea/unmonoqueteclea.github.io/][here]].

If you have been following this blog for some time you will have
noticed that I am not very good at keeping a routine of writing new
blog posts every week (or even every month). There was something that
created a lot of friction in the writing process (even more than the
white paper syndrome): every time I wanted to add new content, usually
after some months with no content, the blog build process was
broken. I spent more time fixing the blog than adding content to
it. This made me move to lightweight blogging systems like [[https://jekyllrb.com/][Jekyll]]. But
it wasn't enough so I decided to embrace minimalism.

What is the very minimal list of features that I need in a blogging
framework?:

- Convert from markup languages such as =markdown= or =org-mode= into
  plain =html=
- Keep an updated *index* page
- Automatically create a =rss.xml= file
- Automatically create an *archive* page and, ideally, another page for
  each *tag*

Just that. Those are the only things that I need. And that is what
[[https://github.com/bastibe/org-static-blog][org-static-blog]] gives me. One single dependency, integrated into
=Emacs=, my OS (well... my code editor). No =Javascript=, just pure =HTML=
and =CSS=.
